-- Migration: Add how_it_works column to destinations table
-- Date: 2025-12-26
-- Description: Adds JSONB column for "How It Works" section (3 steps) per destination

-- Add the column with default value
ALTER TABLE public.destinations
ADD COLUMN IF NOT EXISTS how_it_works jsonb DEFAULT '[
  {"step": 1, "title_es": "Planifica tu Traslado", "title_en": "Plan your Shuttle Service", "description_es": "Tu familia y amigos merecen empezar sus vacaciones sin preocupaciones. En Jetset nos aseguramos de que esto suceda y somos muy flexibles para reservar tu servicio de traslado privado.", "description_en": "You, your family and friends should get right to the good part when going on vacation. At Jetset we make sure that this happens and are highly flexible when it comes to reserving your private shuttle service.", "features_es": ["Disponibilidad 24/7 por WhatsApp", "Nuestro equipo monitorea vuelos y organiza tu llegada", "No te preocupes por manejar o negociar precios", "Siempre proporcionamos la ruta más eficiente"], "features_en": ["24/7 availability over WhatsApp", "Our staff checks flights and organizes your arrival", "You dont need to worry about driving or price negotiations", "We always provide the most efficient route"]},
  {"step": 2, "title_es": "Llegada al Aeropuerto", "title_en": "Arrival at Cancun Airport", "description_es": "Te estaremos esperando a la hora de tu llegada fuera del aeropuerto, para que la transición desde bajar del avión hasta abrir la puerta de tu hotel pase en un abrir y cerrar de ojos.", "description_en": "We will be expecting you at the time of arrival outside the airport, to make the transition from getting out of the plane to opening the door to hotel room pass by in the blink of an eye.", "features_es": ["Nuestro equipo monitorea vuelos y organiza tu llegada", "Te esperamos justo en el aeropuerto", "Comunicación continua con tu conductor por WhatsApp"], "features_en": ["Our staff checks flights and organizes your arrival", "We expect your arrival right at the airport", "Ongoing communication with your driver over WhatsApp or Messenger"]},
  {"step": 3, "title_es": "Transporte a tu Destino", "title_en": "Transportation to your Destination", "description_es": "Nuestros conductores bilingües te llevarán a tu destino de la manera más rápida y segura posible en uno de nuestros vehículos nuevos.", "description_en": "Our bilingual drivers will get you to your destiny in the fastest and safest way possible in one of our brand new shuttles.", "features_es": ["Vehículos nuevos con aire acondicionado de doble zona", "Bebidas frescas incluidas", "Conductores bilingües y certificados"], "features_en": ["New shuttles with Dual Zone Air Conditioning", "Fresh beverages included", "Bilingual and certified drivers"]}
]'::jsonb;

-- Add comment for documentation
COMMENT ON COLUMN public.destinations.how_it_works IS 'JSONB array with 3 steps explaining the booking process. Each step has: step (number), title_es/en, description_es/en, features_es/en (array)';
